"""add received quantity to purchase order items

Revision ID: 686fc3352513
Revises: 88df91a57c03
Create Date: 2026-06-16 23:16:57.722748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686fc3352513'
down_revision: Union[str, Sequence[str], None] = '88df91a57c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'purchase_order_items',
        sa.Column(
            'received_quantity',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.alter_column(
        'purchase_order_items',
        'received_quantity',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'received_quantity')
    # ### end Alembic commands ###
