"""create_production_execution_tables

Revision ID: 75dbc95f9297
Revises: 310a4097f923
Create Date: 2026-06-21 01:08:23.988983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dbc95f9297'
down_revision: Union[str, Sequence[str], None] = '310a4097f923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('quantity_produced', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prod_exec_po_status', 'production_executions', ['production_order_id', 'status'], unique=False)
    op.create_index(op.f('ix_production_executions_id'), 'production_executions', ['id'], unique=False)
    op.create_table('production_execution_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=False),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['production_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'component_product_id', name='uq_exec_items_exec_component')
    )
    op.create_index(op.f('ix_production_execution_items_id'), 'production_execution_items', ['id'], unique=False)
    op.add_column('inventory_transactions', sa.Column('production_execution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_transactions', 'production_executions', ['production_execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'production_execution_id')
    op.drop_index(op.f('ix_production_execution_items_id'), table_name='production_execution_items')
    op.drop_table('production_execution_items')
    op.drop_index(op.f('ix_production_executions_id'), table_name='production_executions')
    op.drop_index('idx_prod_exec_po_status', table_name='production_executions')
    op.drop_table('production_executions')
    # ### end Alembic commands ###
