"""add purchase order reference to inventory transactions

Revision ID: 88df91a57c03
Revises: f8851266edf1
Create Date: 2026-06-16 23:01:46.189777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88df91a57c03'
down_revision: Union[str, Sequence[str], None] = 'f8851266edf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('purchase_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_transactions', 'purchase_orders', ['purchase_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'purchase_order_id')
    # ### end Alembic commands ###
